---
title: "Data Wrangling SMT"
author: "Gabe Riedel, Johnny Young, Will Kapner"
format:
  html:
    theme: default
    warning: false
    
---

```{r Setup}
library(tidyverse)
library(sportyR)
```



Importing the Data
```{r}
setwd("/Users/williamkapner/Documents/CPDataChallenge2023/game_info")
gameinfo1 = read_csv("game_info-1900_01_TeamKJ_TeamB.csv")
setwd("/Users/williamkapner/Documents/CPDataChallenge2023/ball_pos")
location1 = read_csv("ball_pos-1900_01_TeamKJ_TeamB.csv")
location2 = read_csv("ball_pos-1900_02_TeamKJ_TeamB.csv")
setwd("/Users/williamkapner/Documents/CPDataChallenge2023/game_events")
gameevents1 = read_csv("game_events-1900_01_TeamKJ_TeamB.csv")
gameevents2 = read_csv("game_events-1900_02_TeamKJ_TeamB.csv")
setwd("/Users/williamkapner/Documents/CPDataChallenge2023/player_pos_TeamA1")
playerpos1 = read_csv("player_pos-1902_17_TeamMB_TeamA1.csv")
```
```{r}
ballinplay = gameevents1|>
  filter(event_code==4)

a = location1|>
  group_by(play_id)|>
  summarise(timestamp = max(timestamp))

joinedmaxtime = left_join(a, location1, by = "timestamp")

ballpositionfiltered = joinedmaxtime|>
  filter(ball_position_y<=50,ball_position_y>=5)

semi_join(ballinplay,ballpositionfiltered, by = join_by("play_id"=="play_id.x"))


```
```{r}
ballinplay = gameevents2|>
  filter(player_position==5|player_position==3)

right_join(gameevents2,ballinplay)



a = location2|>
  group_by(play_id)|>
  summarise(timestamp = max(timestamp))

joinedmaxtime = left_join(a, location2, by = "timestamp")

ballpositionfiltered = joinedmaxtime|>
  filter(ball_position_y<=50,ball_position_y>=5)

semi_join(ballinplay,ballpositionfiltered, by = join_by("play_id"=="play_id.x"))
```


Work in progress - Mapping play ids onto a baseball field
need to change the scale
```{r}
playid2 = location1|>
  filter(play_id==2)


geom_baseball(league = "MLB")+
  geom_point(data = playid2, aes(x=ball_position_x,y=ball_position_y))

```


## Testing Ideas
First Basemen ranging for ground balls toward second base
first filter to where there's nobody on base
then find ground balls to right side
see when it turns out as a baserunner or an out
who fielded it?
```{r}
gameinfo1|>
  filter(first_baserunner==0, second_baserunner==0, third_baserunner == 0)

plays = data.frame(game_str = character(0))
```

