---
title: "Final Markdown"
author: "Will Kapner, Gabe Riedel, and Johnny Young"
format: 
  html:
    self-contained: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: fenced
  message: false
  warning: false
---


Loading in Packages
```{r Setup}
library(tidyverse)
library(sportyR)
```



Function for reading all files
```{r}
con <- dbConnect(RSQLite::SQLite(), "/Users/williamkapner/Documents/CPDataChallenge2023/data_challenge.db")


# SQL query used to clean bunt data
data_clean_query <- "
SELECT DISTINCT 
    g1.game_str, g1.id, g1.play_id, g1.at_bat, g1.play_per_game, 
    g1.timestamp, g1.player_position, g1.event_code, 
    b.ball_position_x, b.ball_position_y, b.ball_position_z
FROM game_events g1
JOIN game_events g2 
    ON g1.game_str = g2.game_str
    AND g1.id = CAST(CAST(g2.id AS INTEGER) + 1 AS TEXT)
JOIN ball_pos b
    ON g1.game_str = b.game_str
    AND g1.timestamp = b.timestamp
WHERE g1.event_code = 2
AND g2.event_code = 16
AND b.ball_position_y > 5 AND b.ball_position_y < 50
ORDER BY g1.game_str, g1.id;
"

bunt_table <- dbGetQuery(con, data_clean_query)

dbDisconnect(con)

View(bunt_table)
```





Code to determine if a runner has scored
```{r}
score = numeric(0)
games = c()
first = 2653
second = 2196
third = 0
for(i in 1:(nrow(afterbuntplays)-1)){
  count = 0
  if((afterbuntplays[[i,2]]+1)!=afterbuntplays[[i+1,2]]|afterbuntplays[i,1]!=afterbuntplays[i+1,1]){
    if(first!=0){
    if (!(first %in% afterbuntplays[i,4:7])){
    count = count + 1
    }
    }
    if(second!=0){
    if (!(second %in% afterbuntplays[i,4:7])){
    count = count + 1
    }
    }
    if(third!=0){
    if (!(third %in% afterbuntplays[i,4:7])){
    count = count + 1
    }
    }
    score = append(score,count)
    games = append(games,afterbuntplays$game_str[i])
    first = afterbuntplays[i+1,5]
    second = afterbuntplays[i+1,6]
    third =  afterbuntplays[i+1,7]
  }
  if(i==(nrow(afterbuntplays)-1)){
    if(first!=0){
    if (!(first %in% afterbuntplays[i+1,4:7])){
    count = count + 1
    }
    }
    if(second!=0){
    if (!(second %in% afterbuntplays[i+1,4:7])){
    count = count + 1
    }
    }
    if(third!=0){
    if (!(third %in% afterbuntplays[i+1,4:7])){
    count = count + 1
    }
    }
    score = append(score,count)
    games = append(games,afterbuntplays$game_str[i+1])
  }
}

score
games
gamesnew = as.data.frame(games)
scorenew = as.data.frame(score)
fullscores = cbind(gamesnew,scorenew)
write.csv(fullscores, "fullbuntscores.csv", row.names = FALSE)
```


